### ISSUE TITLE
[bug]After change tab in browser, sidebar is disappeared.

### ISSUE THREAD

**Issue by lwngt** [creativetimofficial/ct-paper-dashboard-pro#49]
[condition]
iPad 2018, iOS 13.1.3, Safari

[procedure]
1.open dashboard of Paper Dashboard pro 2 in safari
2.create new tab in safari
3.back to Paper Dashboard pro 2 tab

![Reflector-Recording](https://user-images.githubusercontent.com/46835859/69963771-465a9880-1554-11ea-876d-2be96948f338.gif)

**Comment by groovemen** [comment]
Hello @lwngt,

Thank you for using our products, I would ask you to try to update your iPad because I reproduced this behavior on our device (with IOS v13.2.3) and it works just fine. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21063398/70040562-6d50b300-15c4-11ea-9a63-27515b2d5800.gif)

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by lwngt** [comment]
I checked it on iOS 13.2.3 Safari. Then, I didn't found the issue.
I think the bug was caused by iOS old version.

Thank you your support.

Best regards,
lwngt
