### ISSUE TITLE
Navbar-fixed does not change size with sidebar

### ISSUE THREAD

**Issue by sxotney** [creativetimofficial/ct-paper-dashboard-pro#56]
I followed the implementation rules for fixed navbar here:

https://demos.creative-tim.com/paper-dashboard-pro/documentation/tutorial-components.html?ref=local-documentation-pdp

"Fixed Navbar: If you want to have a "Fixed Navbar" on Desktop and Mobile please add the class navbar-fixed on the tag nav and move the entire nav structure outside of the div with class main-panel. "

The problem is the navbar does not fill the width of the panel when the sidebar is minimised and the browser at large width.

![image](https://user-images.githubusercontent.com/6230394/84376092-71dfcf00-abd8-11ea-9222-c6d7572ed4e7.png)

![image](https://user-images.githubusercontent.com/6230394/84376249-ba978800-abd8-11ea-92bf-0aa37f133cfb.png)

I tried adding an override in the sass files with the below 

```
@media (min-width: $screen-md) {
    .sidebar-mini {  
        .navbar {
            width: $sidebar-mini-width;
        } 
    }
}
```

this seemed to resolve it, only the navbar is set above the sidebar

![image](https://user-images.githubusercontent.com/6230394/84376679-6fca4000-abd9-11ea-858d-4aaf593e1d91.png)

**Comment by groovemen** [comment]
Hello @sxotney,

Thank you for using our products and sorry for this late response. In order to have a sticky navbar, you have to follow these steps:

- set a simple navbar like this:
`<nav class="navbar navbar-expand-lg fixed-top bg-white">...</nav>`
- add the following style for it when the sidebar is expanded: 
>   width: calc(100% - 260px);
>     float: right;
>     margin-left: auto;

- add the following style for the navbar when you have a mini sidebar:
> width: calc(100% - 80px);
>     float: right;
>     margin-left: auto;


And the result will look like this: 

<img width="1680" alt="Screenshot 2020-06-23 at 14 50 34" src="https://user-images.githubusercontent.com/21063398/85401435-abaebf00-b562-11ea-9f62-2d9b07594f05.png">

<img width="1679" alt="Screenshot 2020-06-23 at 14 58 10" src="https://user-images.githubusercontent.com/21063398/85401445-af424600-b562-11ea-8765-454e67e24bae.png">


Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by syonfox** [comment]
```
 body.sidebar-mini .navbar {
        width: calc(100% - 80px);
        float: right;
        margin-left: auto
    }

    .navbar {
        background: #f4f3ef ;
        color: var(--bg-dark-color) !important;
        width: calc(100% - 260px);
        float: right;
        margin-left: auto;
    }

    @media screen and (max-width: 991px) {
         .navbar {
             width: 100%;
         }
    }

```
